name: github_flutter
version: 0.0.1
description: A lightweight high-level GitHub API Client Library that uses Github's v3 API
homepage: https://github.com/IamPekka058/github_flutter

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  http: ^1.3.0
  http_parser:
  json_annotation: ^4.9.0
  meta:

dev_dependencies:
  build_runner: ^2.4.15
  build_test: any
  collection: ^1.15.0
  dependency_validator:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4
  lints: ^5.1.1
  mockito: ^5.0.0
  nock: ^1.0.0
  test: ^1.16.0
  yaml: ^3.0.0
  yaml_edit: ^2.2.0

flutter: